# Generated by Django 4.2.7 on 2025-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('cybersecurity', 'Cybersecurity'), ('software', 'Software Development'), ('cloud', 'Cloud Computing'), ('devops', 'DevOps')], default='software', max_length=50),
        ),
    ]
